### ISSUE TITLE
Hide password with dots (bullets) during authentication

### ISSUE THREAD

**Issue by fyodorio** [latt-dev/latt-cms#1]
no one should see the entered password while entering it

![image](https://user-images.githubusercontent.com/19417873/100840090-317e5100-3497-11eb-8ecc-d1761da49bc7.png)

**Comment by chinmaym07** [comment]
Hey @fyodorio  can I try this. ?

**Comment by fyodorio** [comment]
@chinmaym07 sure, please 👍 let me know if you'll need any assistance

**Comment by chinmaym07** [comment]
Hey @fyodorio  I have opened a PR #11 for this issue. Please Review

**Comment by fyodorio** [comment]
@chinmaym07 thank you very much, great job 🤝
